export enum TILE_TYPE_ENUM{
  WALL_ROW = 'WALL_ROW',      //横墙
  WALL_COLUMN = 'WALL_COLUMN',      //竖墙
  WALL_LEFT_TOP = 'WALL_LEFT_TOP',
  WALL_LEFT_BOTTOM = 'WALL_LEFT_BOTTOM',
  WALL_RIGHT_TOP = 'WALL_RIGHT_TOP',
  WALL_RIGHT_BOTTOM = 'WALL_RIGHT_BOTTOM',
  CLIFF_CENTER = 'CLIFF_CENTER',
  CLIFF_LEFT = 'CLIFF_LEFT',             //左悬崖
  CLIFF_RIGHT = 'CLIFF_RIGHT',           //右悬崖
  FLOOR = 'FLOOR',      //地板

}


export enum EVENT_ENUM{
  NEXT_LEVEL = 'NEXT_LEVEL'
}
